name: GitHub Actions
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  server:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server
    steps:
      - name: Check out the code
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Clean install dependencies
        run: npm ci
      - name: Setup build
        run: npm run build
      - name: Setup test
        run: npm test
        env:
          DATABASE_URI: postgres://fake:fake@localhost:5432/fake
